#!/bin/bash

# Avoid any encoding problems
export LANG=C

# check if messages are to be printed using color
unset txtrst txtbld bldblu bldgrn bldred bldylw
if [[ -t 2 ]]; then
	# prefer terminal safe colobldred and bold text when tput is supported
	if tput setaf 0 &>/dev/null; then
		txtrst="$(tput sgr0)"
		txtbld="$(tput bold)"
		bldblu="${txtbld}$(tput setaf 4)"
		bldgrn="${txtbld}$(tput setaf 2)"
		bldred="${txtbld}$(tput setaf 1)"
		bldylw="${txtbld}$(tput setaf 3)"
		bldpur="${txtbld}$(tput setaf 5)"
		bldcyn="${txtbld}$(tput setaf 6)"
		bldwht="${txtbld}$(tput setaf 7)"
		txtblu="$(tput setaf 4)"
		txtgrn="$(tput setaf 2)"
		txtred="$(tput setaf 1)"
		txtpur="$(tput setaf 5)"
		txtylw="$(tput setaf 3)"
		txtcyn="$(tput setaf 6)"
		txtwht="$(tput setaf 7)"
	else
		txtrst="\e[1;0m"
		txtbld="\e[1;1m"
		bldblu="${txtbld}\e[1;34m"
		bldgrn="${txtbld}\e[1;32m"
		bldred="${txtbld}\e[1;31m"
		bldylw="${txtbld}\e[1;33m"
		bldpur="${txtbld}\e[1;35m" # purple
		bldcyn="${txtbld}\e[1;36m" # cyan
		bldwht="${txtbld}\e[1;37m" # white
		txtred='\e[0;31m' # red
		txtgrn='\e[0;32m' # green
		txtylw='\e[0;33m' # yellow
		txtblu='\e[0;34m' # blue
		txtpur='\e[0;35m' # purple
		txtcyn='\e[0;36m' # cyan
		txtwht='\e[0;37m' # white
	fi
fi
readonly txtrst txtbld bldblu bldgrn bldred bldylw txtred txtgrn txtylw txtblu txtpur txtcyn txtwht

	
	# Feedback indicators
	aaa_any_key="${bldblu} ANY KEY ${bldwht}"
	aaa_any_other_key="${bldblu} ANY OTHER KEY ${bldwht}"
	aaa_ctrl_c="${bldcyn} CTRL-C ${bldwht}"


git_bdate=$(date +%Y%m%d)


# dialog functions *********************************************************************************************************************************************
#***************************************************************************************************************************************************************



function Info()
{

	echo -e "${bldgrn}info-->${bldwht}$@${txtrst}"
}


 function AnyKey()
{
		Info "press ${aaa_any_key} to continue"
		read -n1 -s
}
		
function Fuck()
{
		echo -e "${bldred}ERROR!!!!!!-->${bldwht}$@${txtrst}"
		exit 2
}


function Block()
{

		echo -e "${bldblu}block-->${bldwht}$@${txtrst}"
}

function Warn()
{

		echo -e "${bldylw}WARNING-->${bldwht}$@${txtrst}"
}

function Debug()
{
		if [[ $AAA_DEBUG == yes ]]; then
			echo -e "${bldpur}debug-->${bldwht}$@${txtrst}"
			AnyKey
		fi
}

function DebugTest()
{
		if [[ $AAA_DEBUG == yes ]]; then
			"$@"
			if [[ ! $? -eq 0 ]]; then
				echo -e "${bldpur}debug--> FAILED ---->${bldwht}$@${txtrst}"
				for arg in $@; do
					echo -e "$arg"
				done
			fi
		else
			"$@" || Fuck "$@ failed"
		fi
}

function MenuInactive()
{
	#argument 1 menu key
		# x .. key to display
	#argument 2 text to display
		# xxx .. text to display...
		
		echo -e "${bldwht}key======  ${bldblu}$1${txtcyn} $2 ${txtrst}"
}

function MenuActive()
{
	#argument 1 menu key
		# x .. key to display
	#argument 2 text to display
		# xxx .. text to display...
		
		echo -e "${bldwht}key======  ${bldblu}$1${txtgrn} $2 ${txtrst}"
}

function Test()
{
	
        "$@" || Fuck "$@ failed"
  
}


##
#  usage : in_array( $needle, $haystack )
# return : 0 - found
#          1 - not found
##
InArray() {
	local needle=$1; shift
	local item
	for item in "$@"; do
		[[ $item = $needle ]] && return 0 # Found
	done
	return 1 # Not Found
}


##
#  usage : in_array( $needle, $haystack )
# return : 0 - found
#          1 - not found
##
InList() {
	local needle=$1; shift
	local item
	for item in $1; do
		[[ $item = $needle ]] && return 0 # Found
	done
	return 1 # Not Found
}



function CheckMyDeps()
{
	
	#first argument space delimited list of progs to check for
		#xxxxxx ...variable name name
	
for _checks in $1; do
	command -v $_checks >/dev/null 2>&1
	if [[ ! $? -eq 0 ]]; then
		Warn "----$_checks------ is a dependency for this script, want me to install it?"
		MenuActive "q" "to quit and install $_checks yourself"
		MenuActive "i" "to apt-get install $_checks"
		read -s -n1 aaa_tmpchr
		if [[ ! $aaa_tmpchr == q ]]; then
			apt-get install "$_checks*"
		else
			Fuck "----$_checks------ is a dependency for this script,... quitting untill its met"
		fi
	else
		aaa_escape=1
	fi
done


}



[[ "$(id -u)" != "0" ]] && Fuck "This script must be run as root"

CheckMyDeps "wget pbuilder reprepro cat grep"

function CloneIt()
{
	
	#$1 packages name
	#$2 git url and type ie git/https etc
aaa_escape=0
while [[ $aaa_escape -eq 0 ]]; do

	Info "downloading $2/$1".git
	git clone "$2/$1".git
	if [[ ! $? -eq 0 ]]; then
		Warn "git clone $2/$1 bugged out, mostly due to bad internet"
		Warn "since with this build i cant miss a package i need to try again"
		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
		AnyKey
	else
		aaa_escape=1
	fi
done
}



function SaveSettings()
{



	#first argument is setting variable
		#xxxxxx ...variable name name
	#second argument is value
		#xxxxxx ... value
		
	#if no settings file exists create blank one
	if [[ ! -e "$HOME/.aaa_settings" ]]; then
		echo "#aaa writing initial settings" > "$HOME/.aaa_settings"
	fi
		
	#parse settings file
	#if setting exists delete that line, write new one at same place 
	if [[ $(cat "$HOME/.aaa_settings" | grep "$1") ]]; then
	
		sed -i "s/.*$1.*/$1=\"$2\"/" "$HOME/.aaa_settings"
		if [[ ! $? -eq 0 ]]; then
			Fuck "could not replace line in $HOME/.aaa_settings"
			return 1
		fi
	else
	# if does not exist write new one at bottom
		echo "$1=\"$2\"" >> "$HOME/.aaa_settings"
		if [[ ! $? -eq 0 ]]; then
			Fuck "could not append a line to $HOME/.aaa_settings"
			return 1
		fi
	fi
	return 0
	
}


function MakeADir()
{
	
	#first argument dir path
		#xxxxxx ...variable name name
	
	if [[ ! -d "$1" ]]; then
		Test mkdir -p "$1"
	fi
	
	
}


function DownLoad()
{
	
	#first argument dl link
		#xxxxxx ...variable name name
		
		
aaa_escape=0
while [[ $aaa_escape -eq 0 ]]; do
	wget "$1"
	if [[ ! $? -eq 0 ]]; then
		Warn "wget $1,, bugged out, mostly due to bad internet"
		Warn "since with this build i cant miss this download i need to try again"
		Warn "if thats not good for you ${aaa_ctrl_c} to quit"
		AnyKey
	else
		aaa_escape=1
	fi
done
	
	
}


function CleanMyBuildArea()
{
	local dir_exists
dir_exists=0
if [[ -d "$aaa_work_dir" ]]; then
	Warn "$aaa_work_dir already exists"
	Warn "i need to clean it out sorry"
	rm -rf "$aaa_work_dir"
fi

if [[ -d "$aaa_build_location" ]]; then
	Warn "$aaa_build_location already exists"
	Warn "i need to clean it out sorry"
	rm -rf "$aaa_build_location"
fi

if [[ -d "$aaa_build_result" ]]; then
	Warn "$aaa_build_result already exists"
	Warn "i need to clean it out sorry"
	rm -rf "$aaa_build_result"
fi

MakeADir "$aaa_build_location"
MakeADir "$aaa_work_dir"


}


function UpdateBase()
{

Block "creating/updating base pbuilder image"
aaa_escape=0
if [[ -e "$aaa_base_gz_dir/$aaa_base_gz" ]]; then
	while [[ $aaa_escape -eq 0 ]]; do
		pbuilder --update --override-config
		if [[ ! $? -eq 0 ]]; then
			Warn "pbuilder --update bugged out, mostly due to failed downloads"
			Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
			AnyKey
		else
			aaa_escape=1
		fi
	done
else
	while [[ $aaa_escape -eq 0 ]]; do
		pbuilder --create 
		if [[ ! $? -eq 0 ]]; then
			Warn "pbuilder --update bugged out, mostly due to failed downloads"
			Warn "hence going to try again, if thats not good for you ${aaa_ctrl_c} to quit"
			AnyKey
		else
			aaa_escape=1
		fi
	done
fi


}


function UpdateReadme()
{
if [[ -d "$aaa_git_repo_dir" ]]; then
	
	sed -i  '/^============$/,$d' "$aaa_git_repo_dir/README.md"
	echo -e "============\n"  >> "$aaa_git_repo_dir/README.md"
	
	echo "Kali Packages"  >> "$aaa_git_repo_dir/README.md"
	echo "============="  >> "$aaa_git_repo_dir/README.md"
	sed '/^Installed/,/^Description/d' "$aaa_git_repo_dir/dists/public/kali/binary-amd64/Packages" >> "$aaa_git_repo_dir/README.md"
	sed '/^Installed/,/^Description/d' "$aaa_git_repo_dir/dists/public/kaligit/binary-amd64/Packages" >> "$aaa_git_repo_dir/README.md"
	
	echo "Unstable Packages"  >> "$aaa_git_repo_dir/README.md"
	echo "================="  >> "$aaa_git_repo_dir/README.md"
	sed '/^Installed/,/^Description/d' "$aaa_git_repo_dir/dists/public/unstable/binary-amd64/Packages" >> "$aaa_git_repo_dir/README.md"
	sed '/^Installed/,/^Description/d' "$aaa_git_repo_dir/dists/public/unstablegit/binary-amd64/Packages" >> "$aaa_git_repo_dir/README.md"
fi	
	
}



function RemovePackages()
{
		#first argument repo basedir
		#$2 codename
	
	
	for file_base in `ls *.deb`; do 
		# strip
		local full_pkg_name=${file_base%*_*}
		local pkg_name=${file_base%%_*.*}
		
		Info "Removing $pkg_name from basedir=$1 codename=$2 component=$aaa_component"
		Info "full_pkg_name=$full_pkg_name pkg_name=$pkg_name"
		
		if [[ $1 == "$aaa_work_repo_dir" ]]; then
			reprepro -Vb "$1" remove "$aaa_work_repo_codename" "$pkg_name"
			local list_clean=$(reprepro -Vb "$1" list "$aaa_work_repo_codename" "$pkg_name")
			if [[ $list_clean != "" ]]; then
				Warn "$pkg_name was not removed from work repo ,still exists....$list_clean"
				AnyKey
			fi
		else
			reprepro -Vb "$1" -C "$aaa_component" remove "$2" "$pkg_name"
			local list_clean=$(reprepro -Vb "$1" -C "$aaa_component" list "$2" "$pkg_name")
			if [[ $list_clean != "" ]]; then
				Warn "$pkg_name was not removed still exists....$list_clean"
				AnyKey
			fi
		fi
				
	done
	

}





function AutoIncludeHome()
{
	
	RemovePackages "$aaa_home_repo_dir" "$aaa_home_repo_codename"
	Test reprepro -Vb "$aaa_home_repo_dir" -C "$aaa_component" includedeb "$aaa_home_repo_codename" *.deb
			

}


function AutoIncludeWork()
{
	RemovePackages "$aaa_work_repo_dir" "$aaa_work_repo_codename"
	Test reprepro -Vb "$aaa_work_repo_dir" includedeb "$aaa_work_repo_codename" *.deb

}


function AutoIncludeGit()
{
	
	local source_name=$(grep "Source" *.changes | sed 's/Source: //')
	 Debug "source_name=$source_name aaa_debian_distro=$aaa_debian_distro"
	
		RemovePackages "$aaa_git_repo_dir" "$aaa_git_repo_codename"
		local is_source=$(reprepro -Vb "$aaa_git_repo_dir" -C "$aaa_component" list "$aaa_git_repo_codename" "$source_name" | grep 'source')
		Debug "check for source is" "$is_source"
		if [[ $is_source != "" ]]; then
			Warn "Previous source found--- only including debs to git repo"
			Test reprepro -Vb "$aaa_git_repo_dir" -C "$aaa_component" includedeb "$aaa_git_repo_codename" *.deb
			Debug
		else
			Info "NO previous source found--- including everything in .changes file"
			Test reprepro -Vb "$aaa_git_repo_dir" --ignore=wrongdistribution -C "$aaa_component" include "$aaa_git_repo_codename" *.changes
			Debug
		fi
		UpdateReadme
}


function PatchEm()
{
	
	# seems the hardening wrapper is gone, this just makes sure
	[[ "$aaa_cinnamon_release_list $aaa_cinnamon_git_list" == *"$1"* ]] && sed -i '/hardening-wrapper/d' ./debian/control
	case "$1" in
		#cinnamon build dynamic patches#######################################################################################################################################
			#nemo patches#######################################################################################################################################
			
			nemo) patch -p1 < "$aaa_patch_dir/remove_elevated_privelages_banner.patch" 
				#allow pup-vm to replace gvfs
				Test sed -i 's/gvfs (>= 1.3.2)/gvfs (>= 1.3.2) | pup-volume-monitor/' ./debian/control ;;
		
							
		#libgnome2-0#########################################################################################################################################
		
		libgnome2-0*) Test sed -i 's/gvfs/gvfs | pup-volume-monitor/' ./DEBIAN/control ;;
		
		#gnome-applets#########################################################################################################################################
		
		gnome-applets*) Test sed -i 's/gvfs/gvfs | pup-volume-monitor/' ./DEBIAN/control ;;
			
		#Cinnamon#########################################################################################################################################
		
		Cinnamon) Test sed -i 's/;cinnamon-fallback-mount-helper//' ./files/usr/share/cinnamon-session/sessions/cinnamon.session
							Test sed -i 's/nm-applet;//' ./files/usr/share/cinnamon-session/sessions/cinnamon.session ;;
						
	
	esac
 

}


function PatchDeb() {
	
	# $1 is full deb name
local pkg_raw="$1"
local here=$(pwd)
local tmpdir=`mktemp -d --tmpdir=$aaa_work_dir deb.XXXXXXXXXX`
Debug "$tmpdir"
dpkg-deb -x "$pkg_raw" "$tmpdir"
dpkg-deb --control "$pkg_raw" "$tmpdir/DEBIAN"
cd "$tmpdir"
PatchEm ${pkg_raw%%_*.*}
cd $here
dpkg -b "$tmpdir" "$here/$pkg_raw".aaa.deb
rm -rf "$tmpdir"

}





function SwitchDistro()
{
	Info "Switching distro to $1"
	aaa_debian_distro="$1"
	
	
	if [[ -r "$HOME/.pbuilderrc" ]]; then
		Info "found $HOME/.pbuilderrc from a previous run i hope !!!"
		if [[ $(grep 'DISTRIBUTION=' "$HOME/.pbuilderrc" | sed 's/DISTRIBUTION=//') == "$1" ]]; then
			Info "$HOME/.pbuilderrc already set for $1, no need to switch"
			return 0
		fi
	fi


case "$aaa_debian_distro" in

	kali) aaa_mirror="$aaa_kali_mirror" 
		aaa_base_components="main contrib non-free" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_kali_keyring' '--include=kali-archive-keyring')" ;;
	testing) aaa_mirror="$aaa_deb_mirror" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_base_components="main contrib non-free" ;;
	stable) aaa_mirror="$aaa_deb_mirror" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')" 
		aaa_base_components="main contrib non-free" ;;
	unstable) aaa_mirror="$aaa_deb_mirror" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_deb_keyring')"
		aaa_base_components="main contrib non-free" ;;
	ubuntu) aaa_mirror="$aaa_ubuntu_mirror" 
		aaa_extra_packages="$aaa_extra_packages ubuntu-archive-keyring" 
		aaa_debootstrap_opts="('--variant=buildd' '--keyring=$aaa_ubuntu_keyring' '--include=ubuntu-archive-keyring')"
		aaa_base_components="main restricted universe multiverse" ;;
esac


aaa_cores=$((    $(cat /proc/cpuinfo | grep processor | wc -l)+1    ))

if [[ -z "${architecture}" ]]; then	
	aaa_buildopts="$aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-base.tgz"
else
	aaa_buildopts="--arch $architecture $aaa_extra_build_opts -j$aaa_cores"
	aaa_base_gz="$aaa_debian_distro-$architecture-base.tgz"
fi


#possible extra debootstrapopt
# -m$aaa_maintainer

aaa_apt_cache_dir="$aaa_apt_cache_base_dir/$aaa_debian_distro"

echo "MIRRORSITE=\"$aaa_mirror\"
OTHERMIRROR=\"deb [trusted=yes] file://$aaa_work_repo_dir work main\"
BINDMOUNTS=\"$aaa_bindmounts\"
HOOKDIR=\"$aaa_pbuilder_hookdir\"
EXTRAPACKAGES=\"$aaa_extra_packages\"

APTCACHE=\"$aaa_apt_cache_dir\"
DEBEMAIL=\"$aaa_maintainer\"
BUILDRESULT=\"$aaa_build_result\"
COMPONENTS=\"$aaa_base_components\"
DEBBUILDOPTS=\"$aaa_buildopts\"
DEBOOTSTRAPOPTS=$aaa_debootstrap_opts
BUILDUSERNAME=\"\"
AUTO_DEBSIGN=no
DISTRIBUTION=$aaa_debian_distro
APTCACHEHARDLINK=$aaa_hardlink
BASETGZ=\"$aaa_base_gz_dir/$aaa_base_gz\"
BUILDPLACE=\"$aaa_build_location\"" > "$HOME/.pbuilderrc"

UpdateBase

}

function ActivateWorkRepo() {
	
	#create repro dir struture by downloading , installing,  package
	Block "fill work repo"
	cd "$aaa_work_dir"
	DownLoad "http://dk.archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-keyring/ubuntu-keyring_2012.05.19_all.deb"
	reprepro -b "$aaa_work_repo_dir" includedeb work *.deb > /dev/null 2>&1
	rm -rf *.deb
	cd $HOME

}

function WriteRepo()
{
	#$1 repo local name
	#$2 delete contents of repo dir before writing new
	
	case "$1" in
		$aaa_home_repo_codename) local arches="Architectures: i386 amd64 armel armhf"
				local dir_path="$aaa_home_repo_dir"
				local comps="Components: unstable unstablegit kali kaligit" ;;
				
		$aaa_git_repo_codename) local arches="Architectures: i386 amd64 armel armhf source"
				local dir_path="$aaa_git_repo_dir"
				local comps="Components: unstable unstablegit kali kaligit" ;;
				
		$aaa_work_repo_codename) local arches="Architectures: amd64"
				local dir_path="$aaa_work_repo_dir"
				local comps="Components: main" ;;
	esac
	
	if [[ -z "$aaa_sign_key" ]]; then
		local sign_with_marker=""
		local pass_phrase_marker=""
	else
		local sign_with_marker="SignWith: $aaa_sign_key"
		local pass_phrase_marker="ask-passphrase"
	fi
	
	
	
	if [[ $2 == yes ]]; then
		Warn "repo cleaning was requested about to scrub the contents of $dir_path "
		AnyKey
		Test cd "$dir_path" 
		Test rm -fr `ls -d */`
	fi
	MakeADir "$dir_path/conf"
	
if [[ -e "$dir_path/conf/distributions" ]]; then
	Warn "$dir_path/conf/distributions already exists"
	Warn "backing up original and writing new"
	mv "$dir_path/conf/distributions"  "$dir_path/conf/distributions.backup"
	echo "#config writen by aaa, original config saved to $dir_path/conf/distributions.back " > "$dir_path/conf/distributions"
else

	Info "writing new $dir_path/conf/distributions"
	echo "#config writen by aaa, feel free to modify but dont fuck anything ! " > "$dir_path/conf/distributions"
fi

echo "Origin: aaa.$1.org
Label: aaa-$1-local-repo
Codename: $1
Suite: $aaa_default_distro
Version: 1.0
$arches
$comps
Description: local custom repo for $1 packages
$sign_with_marker" >> "$dir_path/conf/distributions"

Block "writing $dir_path/conf/options"

if [[ -e "$dir_path/conf/options" ]]; then
	Warn "$dir_path/conf/options already exists"
	Warn "backing up original and writing new"
	mv "$dir_path/conf/options"  "$dir_path/conf/options.backup"
	echo "#config writen by aaa, original config saved to $dir_path/conf/options.back " > "$dir_path/conf/options"
else

	Info "writing new $dir_path/conf/options"
	echo "#config writen by aaa, feel free to modify but dont fuck anything ! " > "$dir_path/conf/options"
fi
Test echo "verbose
basedir $dir_path
$pass_phrase_marker" >> "$dir_path/conf/options"

reprepro -b "$dir_path" createsymlinks "$1"
	
}


